// flow-typed signature: 271744c458c6ace6d13a32f3ffa135f1
// flow-typed version: <<STUB>>/electron-titlebar-windows_v^3.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-titlebar-windows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-titlebar-windows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-titlebar-windows/app/main' {
  declare module.exports: any;
}

declare module 'electron-titlebar-windows/lib/titlebar' {
  declare module.exports: any;
}

declare module 'electron-titlebar-windows/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-titlebar-windows/app/main.js' {
  declare module.exports: $Exports<'electron-titlebar-windows/app/main'>;
}
declare module 'electron-titlebar-windows/lib/titlebar.js' {
  declare module.exports: $Exports<'electron-titlebar-windows/lib/titlebar'>;
}
declare module 'electron-titlebar-windows/test/test.js' {
  declare module.exports: $Exports<'electron-titlebar-windows/test/test'>;
}
