// flow-typed signature: a576b48081ff7de08ae2f6d558d03014
// flow-typed version: <<STUB>>/i_v^0.3.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i/lib/defaults' {
  declare module.exports: any;
}

declare module 'i/lib/inflect' {
  declare module.exports: any;
}

declare module 'i/lib/inflections' {
  declare module.exports: any;
}

declare module 'i/lib/methods' {
  declare module.exports: any;
}

declare module 'i/lib/native' {
  declare module.exports: any;
}

declare module 'i/lib/util' {
  declare module.exports: any;
}

declare module 'i/test/inflector/cases' {
  declare module.exports: any;
}

declare module 'i/test/inflector/inflections-test' {
  declare module.exports: any;
}

declare module 'i/test/inflector/methods-test' {
  declare module.exports: any;
}

declare module 'i/test/utils/array-test' {
  declare module.exports: any;
}

declare module 'i/test/utils/string-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i/lib/defaults.js' {
  declare module.exports: $Exports<'i/lib/defaults'>;
}
declare module 'i/lib/inflect.js' {
  declare module.exports: $Exports<'i/lib/inflect'>;
}
declare module 'i/lib/inflections.js' {
  declare module.exports: $Exports<'i/lib/inflections'>;
}
declare module 'i/lib/methods.js' {
  declare module.exports: $Exports<'i/lib/methods'>;
}
declare module 'i/lib/native.js' {
  declare module.exports: $Exports<'i/lib/native'>;
}
declare module 'i/lib/util.js' {
  declare module.exports: $Exports<'i/lib/util'>;
}
declare module 'i/test/inflector/cases.js' {
  declare module.exports: $Exports<'i/test/inflector/cases'>;
}
declare module 'i/test/inflector/inflections-test.js' {
  declare module.exports: $Exports<'i/test/inflector/inflections-test'>;
}
declare module 'i/test/inflector/methods-test.js' {
  declare module.exports: $Exports<'i/test/inflector/methods-test'>;
}
declare module 'i/test/utils/array-test.js' {
  declare module.exports: $Exports<'i/test/utils/array-test'>;
}
declare module 'i/test/utils/string-test.js' {
  declare module.exports: $Exports<'i/test/utils/string-test'>;
}
