// flow-typed signature: 56e87a104f2e51862108f94a0092317a
// flow-typed version: <<STUB>>/mui-datatables_v^2.0.0-beta.59/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mui-datatables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mui-datatables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mui-datatables/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mui-datatables/dist/index.js' {
  declare module.exports: $Exports<'mui-datatables/dist/index'>;
}
