// flow-typed signature: 4a3730bd430e5f9c328f1d081a9ee4b6
// flow-typed version: <<STUB>>/react-spinners_v^0.5.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/vendor' {
  declare module.exports: any;
}

declare module 'react-spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/code' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/color_picker' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/form' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/index' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/loader_item' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/index' {
  declare module.exports: any;
}

declare module 'react-spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/index' {
  declare module.exports: any;
}

declare module 'react-spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/helpers/index' {
  declare module.exports: any;
}

declare module 'react-spinners/src/index' {
  declare module.exports: any;
}

declare module 'react-spinners/src/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/BarLoader'>;
}
declare module 'react-spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/BeatLoader'>;
}
declare module 'react-spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/BounceLoader'>;
}
declare module 'react-spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/CircleLoader'>;
}
declare module 'react-spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClipLoader'>;
}
declare module 'react-spinners/docs/bundle.js' {
  declare module.exports: $Exports<'react-spinners/docs/bundle'>;
}
declare module 'react-spinners/docs/vendor.js' {
  declare module.exports: $Exports<'react-spinners/docs/vendor'>;
}
declare module 'react-spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/DotLoader'>;
}
declare module 'react-spinners/examples/components/code.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/code'>;
}
declare module 'react-spinners/examples/components/color_picker.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/color_picker'>;
}
declare module 'react-spinners/examples/components/form.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/form'>;
}
declare module 'react-spinners/examples/components/index.js' {
  declare module.exports: $Exports<'react-spinners/examples/components/index'>;
}
declare module 'react-spinners/examples/components/loader_item.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/loader_item'>;
}
declare module 'react-spinners/examples/index.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/index'>;
}
declare module 'react-spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/FadeLoader'>;
}
declare module 'react-spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/GridLoader'>;
}
declare module 'react-spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/HashLoader'>;
}
declare module 'react-spinners/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/helpers/index'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/MoonLoader'>;
}
declare module 'react-spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/PacmanLoader'>;
}
declare module 'react-spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/PropagateLoader'>;
}
declare module 'react-spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/PulseLoader'>;
}
declare module 'react-spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/RingLoader'>;
}
declare module 'react-spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/RiseLoader'>;
}
declare module 'react-spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/RotateLoader'>;
}
declare module 'react-spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/ScaleLoader'>;
}
declare module 'react-spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/SkewLoader'>;
}
declare module 'react-spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/SquareLoader'>;
}
declare module 'react-spinners/src/BarLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BarLoader'>;
}
declare module 'react-spinners/src/BeatLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BeatLoader'>;
}
declare module 'react-spinners/src/BounceLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BounceLoader'>;
}
declare module 'react-spinners/src/CircleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/CircleLoader'>;
}
declare module 'react-spinners/src/ClimbingBoxLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ClimbingBoxLoader'>;
}
declare module 'react-spinners/src/ClipLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ClipLoader'>;
}
declare module 'react-spinners/src/DotLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/DotLoader'>;
}
declare module 'react-spinners/src/FadeLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/FadeLoader'>;
}
declare module 'react-spinners/src/GridLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/GridLoader'>;
}
declare module 'react-spinners/src/HashLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/HashLoader'>;
}
declare module 'react-spinners/src/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/src/helpers/index'>;
}
declare module 'react-spinners/src/index.js' {
  declare module.exports: $Exports<'react-spinners/src/index'>;
}
declare module 'react-spinners/src/MoonLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/MoonLoader'>;
}
declare module 'react-spinners/src/PacmanLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PacmanLoader'>;
}
declare module 'react-spinners/src/PropagateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PropagateLoader'>;
}
declare module 'react-spinners/src/PulseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PulseLoader'>;
}
declare module 'react-spinners/src/RingLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RingLoader'>;
}
declare module 'react-spinners/src/RiseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RiseLoader'>;
}
declare module 'react-spinners/src/RotateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RotateLoader'>;
}
declare module 'react-spinners/src/ScaleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ScaleLoader'>;
}
declare module 'react-spinners/src/SkewLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SkewLoader'>;
}
declare module 'react-spinners/src/SquareLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SquareLoader'>;
}
declare module 'react-spinners/src/SyncLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SyncLoader'>;
}
declare module 'react-spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/SyncLoader'>;
}
declare module 'react-spinners/webpack.config.js' {
  declare module.exports: $Exports<'react-spinners/webpack.config'>;
}
