// flow-typed signature: a66a2fa024c56935f3c44654fb25ec2a
// flow-typed version: <<STUB>>/react-loader-spinner_v^2.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader-spinner/dist/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/BallTriangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/CradleLoader' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/MutatingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Plane' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RevolvingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/TailSpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ThreeDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Watch' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/scripts/mocha_runner' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/BallTriangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/CradleLoader' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/MutatingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Plane' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/RevolvingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/TailSpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/ThreeDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loader/Watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader-spinner/dist/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/index'>;
}
declare module 'react-loader-spinner/dist/loader/Audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Audio'>;
}
declare module 'react-loader-spinner/dist/loader/BallTriangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/BallTriangle'>;
}
declare module 'react-loader-spinner/dist/loader/Bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Bars'>;
}
declare module 'react-loader-spinner/dist/loader/Circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Circles'>;
}
declare module 'react-loader-spinner/dist/loader/CradleLoader.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/CradleLoader'>;
}
declare module 'react-loader-spinner/dist/loader/Grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Grid'>;
}
declare module 'react-loader-spinner/dist/loader/Hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Hearts'>;
}
declare module 'react-loader-spinner/dist/loader/MutatingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/MutatingDot'>;
}
declare module 'react-loader-spinner/dist/loader/Oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Oval'>;
}
declare module 'react-loader-spinner/dist/loader/Plane.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Plane'>;
}
declare module 'react-loader-spinner/dist/loader/Puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Puff'>;
}
declare module 'react-loader-spinner/dist/loader/RevolvingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RevolvingDot'>;
}
declare module 'react-loader-spinner/dist/loader/Rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Rings'>;
}
declare module 'react-loader-spinner/dist/loader/TailSpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/TailSpin'>;
}
declare module 'react-loader-spinner/dist/loader/ThreeDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ThreeDots'>;
}
declare module 'react-loader-spinner/dist/loader/Triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Triangle'>;
}
declare module 'react-loader-spinner/dist/loader/Watch.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Watch'>;
}
declare module 'react-loader-spinner/index' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
declare module 'react-loader-spinner/index.js' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
declare module 'react-loader-spinner/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-loader-spinner/scripts/mocha_runner'>;
}
declare module 'react-loader-spinner/src/__tests__/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/__tests__/index'>;
}
declare module 'react-loader-spinner/src/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/index'>;
}
declare module 'react-loader-spinner/src/loader/Audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Audio'>;
}
declare module 'react-loader-spinner/src/loader/BallTriangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/BallTriangle'>;
}
declare module 'react-loader-spinner/src/loader/Bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Bars'>;
}
declare module 'react-loader-spinner/src/loader/Circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Circles'>;
}
declare module 'react-loader-spinner/src/loader/CradleLoader.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/CradleLoader'>;
}
declare module 'react-loader-spinner/src/loader/Grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Grid'>;
}
declare module 'react-loader-spinner/src/loader/Hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Hearts'>;
}
declare module 'react-loader-spinner/src/loader/MutatingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/MutatingDot'>;
}
declare module 'react-loader-spinner/src/loader/Oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Oval'>;
}
declare module 'react-loader-spinner/src/loader/Plane.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Plane'>;
}
declare module 'react-loader-spinner/src/loader/Puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Puff'>;
}
declare module 'react-loader-spinner/src/loader/RevolvingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/RevolvingDot'>;
}
declare module 'react-loader-spinner/src/loader/Rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Rings'>;
}
declare module 'react-loader-spinner/src/loader/TailSpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/TailSpin'>;
}
declare module 'react-loader-spinner/src/loader/ThreeDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/ThreeDots'>;
}
declare module 'react-loader-spinner/src/loader/Triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Triangle'>;
}
declare module 'react-loader-spinner/src/loader/Watch.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loader/Watch'>;
}
