// flow-typed signature: 94b5a3f8ec772a8e0e485e8765a8cd2b
// flow-typed version: <<STUB>>/terminal-in-react_v^4.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminal-in-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminal-in-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terminal-in-react/lib/bundle/terminal-react' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/command' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/example' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/examples' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/help' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/option' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/options' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/parse' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/args/utils' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Bar/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Bar/styled-elements' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Content/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Content/styled-elements' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Plugin' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Tabs/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Tabs/styled-elements' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Terminal/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Terminal/styled-elements' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/Terminal/terminal-utils' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/components/types' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/index' {
  declare module.exports: any;
}

declare module 'terminal-in-react/lib/js/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terminal-in-react/lib/bundle/terminal-react.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/bundle/terminal-react'>;
}
declare module 'terminal-in-react/lib/js/args/command.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/command'>;
}
declare module 'terminal-in-react/lib/js/args/example.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/example'>;
}
declare module 'terminal-in-react/lib/js/args/examples.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/examples'>;
}
declare module 'terminal-in-react/lib/js/args/help.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/help'>;
}
declare module 'terminal-in-react/lib/js/args/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/index'>;
}
declare module 'terminal-in-react/lib/js/args/option.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/option'>;
}
declare module 'terminal-in-react/lib/js/args/options.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/options'>;
}
declare module 'terminal-in-react/lib/js/args/parse.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/parse'>;
}
declare module 'terminal-in-react/lib/js/args/utils.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/args/utils'>;
}
declare module 'terminal-in-react/lib/js/components/Bar/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Bar/index'>;
}
declare module 'terminal-in-react/lib/js/components/Bar/styled-elements.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Bar/styled-elements'>;
}
declare module 'terminal-in-react/lib/js/components/Content/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Content/index'>;
}
declare module 'terminal-in-react/lib/js/components/Content/styled-elements.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Content/styled-elements'>;
}
declare module 'terminal-in-react/lib/js/components/Plugin.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Plugin'>;
}
declare module 'terminal-in-react/lib/js/components/Tabs/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Tabs/index'>;
}
declare module 'terminal-in-react/lib/js/components/Tabs/styled-elements.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Tabs/styled-elements'>;
}
declare module 'terminal-in-react/lib/js/components/Terminal/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Terminal/index'>;
}
declare module 'terminal-in-react/lib/js/components/Terminal/styled-elements.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Terminal/styled-elements'>;
}
declare module 'terminal-in-react/lib/js/components/Terminal/terminal-utils.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/Terminal/terminal-utils'>;
}
declare module 'terminal-in-react/lib/js/components/types.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/components/types'>;
}
declare module 'terminal-in-react/lib/js/index.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/index'>;
}
declare module 'terminal-in-react/lib/js/utils.js' {
  declare module.exports: $Exports<'terminal-in-react/lib/js/utils'>;
}
